[phases.setup]
nixPkgs = ["nodejs_18", "php81", "php81Packages.composer"]

[phases.install]
cmds = [
    "cd src",
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build"
]

[phases.build]
cmds = [
    "cd src",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "cd src && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT" 